export const menuData = [
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "大排面",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "1",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "鱼香肉丝",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "2",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "蛋炒饭",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "3",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "红烧排骨",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "4",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "草头",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "5",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "素鸡",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "6",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "麻婆豆腐",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "7",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "红烧肉",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "8",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "紫菜汤",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "9",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "番茄炒蛋",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "10",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "毛豆梭子蟹",
    foodType: ["hc", "zs"],
    material: ["1"],
    menuId: "11",
    season: ["1", "2"],
  },
];
