export const menuData = [
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "大排面",
    foodType: ["zs"],
    material: ["1"],
    foodId: "1",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "鱼香肉丝",
    foodType: ["hc"],
    material: ["1"],
    foodId: "2",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "蛋炒饭",
    foodType: ["zs"],
    material: ["1"],
    foodId: "3",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "红烧排骨",
    foodType: ["hc"],
    material: ["1"],
    foodId: "4",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "草头",
    foodType: ["zs"],
    material: ["1"],
    foodId: "5",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "素鸡",
    foodType: ["zs"],
    material: ["1"],
    foodId: "6",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "麻婆豆腐",
    foodType: ["hc"],
    material: ["1"],
    foodId: "7",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "红烧肉",
    foodType: ["hc"],
    material: ["1"],
    foodId: "8",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "紫菜汤",
    foodType: ["tl"],
    material: ["1"],
    foodId: "9",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "番茄炒蛋",
    foodType: ["hc"],
    material: ["1"],
    foodId: "10",
    season: ["1", "2"],
  },
  {
    createdBy: "admin",
    createdTime: 1629988224085,
    desc: "",
    foodName: "毛豆梭子蟹",
    foodType: ["hc"],
    material: ["1"],
    foodId: "11",
    season: ["1", "2"],
  },
];
